### ISSUE TITLE
redirect : Issue 

### ISSUE THREAD

**Issue by ASf4646** [TusharVashishth/daily-dev-clone#1] opened 2024-04-05 02:23 UTC
![image](https://github.com/TusharVashishth/daily-dev-clone/assets/132731011/d0660a29-819d-4e4c-8912-984d141631c9)
![image](https://github.com/TusharVashishth/daily-dev-clone/assets/132731011/a30141f8-f86e-427f-a77b-c9514d597ce4)
![image](https://github.com/TusharVashishth/daily-dev-clone/assets/132731011/4e14cd5a-6ee2-4330-8c90-8e7ef9f6d8d9)
![image](https://github.com/TusharVashishth/daily-dev-clone/assets/132731011/3973bbbc-02e4-4626-adb6-895a36db28b2)

Salam Sir! 
Sir jab hum login kartay hain to login successfully ka toast to a jata hai but redirection ka error a raha hai uppar screenshot attach hain 2 din se solve kar raha but ni ho raha ap kuch help kar dien sir ?? tik tok apka copy bhi kiya hai but ni ho raha sir 
from: Pakistan

**Comment by ASf4646** [comment] 2024-04-05 02:25
![image](https://github.com/TusharVashishth/daily-dev-clone/assets/132731011/fff50697-173a-43b4-89d5-f9e591f3b2bd)

**Comment by TusharVashishth** [comment] 2024-04-05 03:55
Pls make sure ki apne callbackUrl mai sahi url dala ho in signIn() method
mai jo next auth provide krta hai

**Comment by ASf4646** [comment] 2024-04-05 07:35
![image](https://github.com/TusharVashishth/daily-dev-clone/assets/132731011/89239357-b0f7-4d16-99e3-a92959efc901)


G sir home page ka url dala hai

**Comment by ASf4646** [comment] 2024-04-05 07:36
Sir kaha pe masla a raha ho ga ??

**Comment by TusharVashishth** [comment] 2024-04-05 08:05
And apne jo authOptions ki file hai vahan pages object ke under login url /
laga rakha hai na ?

**Comment by ASf4646** [comment] 2024-04-05 08:19
![image](https://github.com/TusharVashishth/daily-dev-clone/assets/132731011/caa675d8-875c-42fe-b7fb-33b432a42144)

**Comment by TusharVashishth** [comment] 2024-04-05 17:08
The issue is resolved now. So I am closing this Issue

**Closed** 2024-04-05 17:08 UTC
